import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
    faHome,
    faSearch,
    faExternalLinkAlt,
    faArrowUp,
    faCaretLeft,
    faCaretRight,
    faCaretDown,
    faInfoCircle,
    faExclamationCircle,
    faQuestionCircle,
    faPlay,
    faExpandAlt,
    faTimes,
    faRedo,
    faArrowLeft,
    faArrowRight,
    faCog,
    faHeart,
    faSortAmountUp,
    faSyncAlt,
    faEye,
    faEyeSlash,
    faTrash,
    faHistory,
    faCheckCircle,
    faFilter,
    faCalendarAlt,
    faCaretUp,
    faBookOpen,
    faExchangeAlt,
    faBookmark,
    faChevronLeft,
    faChevronRight,
    faLink,
    faSignInAlt,
    faUser,
    faSignOutAlt,
    faSun,
    faMoon,
    faBars,
    faClipboard,
    faCheck,
    faPause,
    faVolumeUp,
    faVolumeMute,
    faVolumeDown,
    faCompressAlt,
    faForward,
    faBackward,
    faFastForward,
    faVideo
} from "@fortawesome/free-solid-svg-icons";
import {
    faSnowflake,
    faWindowMinimize,
    faWindowMaximize,
    faHeart as faUnfilledHeart,
    faBookmark as faUnfilledBookmark
} from "@fortawesome/free-regular-svg-icons";
import {
    faDiscord,
    faGithub,
    faPatreon
} from "@fortawesome/free-brands-svg-icons";

config.searchPseudoElements = true;

library.add(
    faHome,
    faSearch,
    faSnowflake,
    faExternalLinkAlt,
    faArrowUp,
    faCaretLeft,
    faCaretRight,
    faCaretDown,
    faInfoCircle,
    faExclamationCircle,
    faQuestionCircle,
    faPlay,
    faWindowMinimize,
    faExpandAlt,
    faWindowMaximize,
    faTimes,
    faRedo,
    faArrowLeft,
    faArrowRight,
    faCog,
    faHeart,
    faSortAmountUp,
    faSyncAlt,
    faEye,
    faEyeSlash,
    faTrash,
    faHistory,
    faCheckCircle,
    faFilter,
    faCalendarAlt,
    faCaretUp,
    faDiscord,
    faBookOpen,
    faPatreon,
    faGithub,
    faExchangeAlt,
    faUnfilledHeart,
    faBookmark,
    faUnfilledBookmark,
    faChevronLeft,
    faChevronRight,
    faLink,
    faSignInAlt,
    faUser,
    faSignOutAlt,
    faSun,
    faMoon,
    faBars,
    faClipboard,
    faCheck,
    faPause,
    faVolumeUp,
    faVolumeMute,
    faVolumeDown,
    faCompressAlt,
    faForward,
    faBackward,
    faFastForward,
    faVideo
);

export default FontAwesomeIcon;
